import { ArrowRight, CalendarDays, ClipboardList, Plus, UserRound, UsersRound } from 'lucide-react';
import { Link } from 'wouter';
import { useGetDashboard } from '@workspace/api-client-react';
import { EventRow, ErrorState, LoadingState, ProfileAvatar } from '@/components/shared';

export default function DashboardPage() {
  const dashboard = useGetDashboard();
  if (dashboard.isLoading) return <LoadingState lines={6} />;
  if (dashboard.isError || !dashboard.data) return <ErrorState onRetry={() => dashboard.refetch()} />;
  const data = dashboard.data;
  const active = data.profiles.find((p) => p.id === data.activeProfileId) ?? data.profiles[0];
  return <div className="animate-rise space-y-9" data-testid="page-dashboard">
    <section className="relative overflow-hidden rounded-[2rem] border border-[#d9edf8] bg-white px-6 py-8 sm:px-10 sm:py-10">
      <div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-[#edf8ff]" /><div className="absolute -bottom-24 right-24 h-48 w-48 rounded-full border-[24px] border-[#f4fbff]" />
      <div className="relative max-w-2xl"><p className="text-sm font-semibold text-[#4a87ad]">Welcome back</p><h1 className="mt-3 max-w-xl font-serif text-4xl leading-[1.08] tracking-[-.03em] text-[#183b59] sm:text-5xl">Your family’s health, <span className="text-[#398ac0]">remembered.</span></h1><p className="mt-4 max-w-lg text-[15px] leading-7 text-[#71899d]">A simple place to keep the visits, questions, and small details you want to remember.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/timeline?new=1" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#267db8] px-4 text-sm font-bold text-white shadow-[0_8px_18px_rgba(38,125,184,.16)] transition hover:bg-[#1f6fa5]" data-testid="link-hero-add-memory"><Plus className="h-4 w-4" />Add health memory</Link><Link href="/profiles" className="inline-flex h-11 items-center gap-2 rounded-xl border border-[#c9e0ee] bg-white px-4 text-sm font-bold text-[#3b7196] transition hover:bg-[#f2f9fd]" data-testid="link-hero-family"><UsersRound className="h-4 w-4" />View people</Link></div></div>
    </section>
    <section className="grid gap-4 sm:grid-cols-[1.25fr_.75fr]">
      <div className="rounded-2xl border border-[#deebf4] bg-white p-5 sm:p-6" data-testid="section-family"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#7b99ad]">Your family</p><h2 className="mt-1 font-serif text-2xl text-[#183b59]">People to care for</h2></div><Link href="/profiles" className="text-sm font-bold text-[#3785b4] hover:text-[#1c608d]" data-testid="link-view-profiles">See all</Link></div>{data.profiles.length ? <div className="mt-5 flex flex-wrap gap-3">{data.profiles.slice(0, 4).map((profile) => <Link href={`/profiles/${profile.id}`} key={profile.id} className="flex min-w-[150px] flex-1 items-center gap-3 rounded-xl border border-[#e5f0f6] bg-[#fbfdff] p-3 transition hover:border-[#b9dced] hover:bg-[#f5fbff]" data-testid={`card-family-member-${profile.id}`}><ProfileAvatar profile={profile} size="sm" /><span className="min-w-0"><span className="block truncate text-sm font-bold text-[#244b68]">{profile.name}</span><span className="mt-0.5 block text-xs text-[#829bad]">{profile.relationship}</span></span></Link>)}<Link href="/profiles" className="flex min-w-[150px] flex-1 items-center justify-center gap-2 rounded-xl border border-dashed border-[#b8d8e9] p-3 text-sm font-bold text-[#3785b4] transition hover:bg-[#f3faff]" data-testid="link-add-family-member"><Plus className="h-4 w-4" />Add family member</Link></div> : <div className="mt-5 flex items-center justify-between gap-4 rounded-xl bg-[#f4faff] p-4"><p className="text-sm text-[#71899d]">Add the people whose health you want to remember.</p><Link href="/profiles" className="shrink-0 text-sm font-bold text-[#3785b4]" data-testid="link-add-first-member">Add someone</Link></div>}</div>
      <div className="rounded-2xl border border-[#deebf4] bg-[#edf8ff] p-5 sm:p-6" data-testid="card-quick-action"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[#378ac0]"><ClipboardList className="h-5 w-5" /></div><p className="mt-5 text-xs font-bold uppercase tracking-[.1em] text-[#5b91b2]">A quick note</p><h2 className="mt-1 font-serif text-2xl leading-tight text-[#1c5275]">What happened?</h2><p className="mt-2 text-sm leading-6 text-[#6d91a6]">Save a visit, a symptom, a test, or anything worth finding later.</p><Link href="/timeline?new=1" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#2675a9]" data-testid="link-quick-add">Add a health memory <ArrowRight className="h-4 w-4" /></Link></div>
    </section>
    <div className="grid gap-8 xl:grid-cols-[1.4fr_.7fr]">
      <section><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#7b99ad]">Recently added</p><h2 className="mt-1 font-serif text-2xl text-[#183b59]">Health memories</h2></div><Link href="/timeline" className="flex items-center gap-1 text-sm font-bold text-[#3785b4] hover:text-[#1c608d]" data-testid="link-view-all-events">View timeline <ArrowRight className="h-4 w-4" /></Link></div><div className="space-y-3">{data.recentEvents.length ? data.recentEvents.map((event) => <EventRow key={event.id} event={event} profile={data.profiles.find((p) => p.id === event.profileId)} />) : <div className="rounded-2xl border border-dashed border-[#c7dfed] bg-white p-8"><p className="font-serif text-lg text-[#244b68]">Your first memory can start here.</p><p className="mt-1 text-sm text-[#778fa1]">A short note is enough.</p></div>}</div></section>
      <aside className="space-y-4"><div className="rounded-2xl border border-[#deebf4] bg-white p-6"><div className="flex items-center justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf7fd] text-[#3c86b3]"><CalendarDays className="h-5 w-5" /></div><span className="text-3xl font-semibold tracking-[-.04em] text-[#1d587b]">{data.upcomingReminders}</span></div><h3 className="mt-5 font-serif text-xl text-[#1d4563]">Upcoming follow-ups</h3><p className="mt-1 text-sm leading-6 text-[#7892a5]">Keep the next step somewhere easy to find.</p><Link href="/reminders" className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#3785b4]" data-testid="link-dashboard-reminders">View follow-ups <ArrowRight className="h-4 w-4" /></Link></div>{active ? <div className="rounded-2xl border border-[#deebf4] bg-white p-6"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#7b99ad]">Currently viewing</p><div className="mt-4 flex items-center gap-3"><ProfileAvatar profile={active} size="md" /><div><h3 className="font-serif text-xl text-[#1d4563]">{active.name}</h3><p className="text-xs text-[#7d96a8]">{active.relationship} · {active.eventCount} memories</p></div></div><Link href={`/profiles/${active.id}`} className="mt-5 flex items-center justify-between border-t border-[#e5eff5] pt-4 text-sm font-bold text-[#3785b4]" data-testid={`link-active-profile-${active.id}`}>Open profile <ArrowRight className="h-4 w-4" /></Link></div> : <div className="rounded-2xl border border-dashed border-[#c7dfed] bg-white p-6 text-center"><UserRound className="mx-auto h-5 w-5 text-[#73a8c7]" /><p className="mt-3 text-sm font-semibold text-[#52758c]">Add someone to get started.</p></div>}</aside>
    </div>
  </div>;
}