import { ArrowUpRight, CalendarDays, ClipboardList, HeartPulse, Plus, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { useGetDashboard } from '@workspace/api-client-react';
import { EventRow, ErrorState, LoadingState, ProfileAvatar, Button } from '@/components/shared';

export default function DashboardPage() {
  const dashboard = useGetDashboard();
  if (dashboard.isLoading) return <LoadingState lines={6} />;
  if (dashboard.isError || !dashboard.data) return <ErrorState onRetry={() => dashboard.refetch()} />;
  const data = dashboard.data;
  const active = data.profiles.find((p) => p.id === data.activeProfileId) ?? data.profiles[0];
  return <div className="animate-rise space-y-9" data-testid="page-dashboard">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#dcebe0] px-6 py-8 sm:px-10 sm:py-10">
      <div className="absolute -right-10 -top-20 h-64 w-64 rounded-full border-[30px] border-[#bdd8c8]/70" /><div className="absolute -bottom-20 right-32 h-48 w-48 rounded-full border-[20px] border-[#c9e0cf]/80" />
      <div className="relative max-w-2xl"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#417368]"><Sparkles className="h-4 w-4" />Good to have you here</div><h1 className="mt-4 max-w-xl font-serif text-4xl leading-[1.08] tracking-[-.03em] text-[#173f48] sm:text-5xl">Your family’s health, <em className="text-[#4f8678]">held together.</em></h1><p className="mt-4 max-w-lg text-[15px] leading-7 text-[#53716e]">A clear place for the visits, questions, and little details that are easy to lose track of.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/timeline?new=1" className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#173f48] px-4 text-sm font-bold text-[#fffdf8] shadow-[0_8px_20px_rgba(23,63,72,.13)] transition hover:bg-[#245764]" data-testid="link-hero-add-memory"><Plus className="h-4 w-4" />Add a memory</Link><Link href="/profiles" className="inline-flex h-11 items-center gap-2 rounded-xl border border-[#a8c6b2] bg-[#eef6ec]/70 px-4 text-sm font-bold text-[#326258] transition hover:bg-[#f5faf1]" data-testid="link-hero-family"><span>See family profiles</span><ArrowUpRight className="h-4 w-4" /></Link></div></div>
    </section>
    <section className="grid gap-4 sm:grid-cols-3" aria-label="Family health at a glance">
      <div className="rounded-2xl border border-[#e4e5dc] bg-[#fffdf8] p-5" data-testid="stat-family-members"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.12em] text-[#81908b]">Family members</span><div className="rounded-xl bg-[#e9f1e9] p-2 text-[#4f8275]"><HeartPulse className="h-4 w-4" /></div></div><p className="mt-4 font-serif text-3xl text-[#173f48]">{data.profiles.length}</p><p className="mt-1 text-sm text-[#7c8985]">profiles in your vault</p></div>
      <div className="rounded-2xl border border-[#e4e5dc] bg-[#fffdf8] p-5" data-testid="stat-events-month"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.12em] text-[#81908b]">Memories this month</span><div className="rounded-xl bg-[#f6edda] p-2 text-[#9a7c36]"><ClipboardList className="h-4 w-4" /></div></div><p className="mt-4 font-serif text-3xl text-[#173f48]">{data.eventsThisMonth}</p><p className="mt-1 text-sm text-[#7c8985]">details kept close</p></div>
      <div className="rounded-2xl border border-[#e4e5dc] bg-[#fffdf8] p-5" data-testid="stat-upcoming-reminders"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.12em] text-[#81908b]">Coming up</span><div className="rounded-xl bg-[#e8edf2] p-2 text-[#526e83]"><CalendarDays className="h-4 w-4" /></div></div><p className="mt-4 font-serif text-3xl text-[#173f48]">{data.upcomingReminders}</p><p className="mt-1 text-sm text-[#7c8985]">follow-ups to remember</p></div>
    </section>
    <div className="grid gap-8 xl:grid-cols-[1.45fr_.75fr]"><section><div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#66837d]">The latest chapter</p><h2 className="mt-1 font-serif text-2xl text-[#173f48]">Recent health memories</h2></div><Link href="/timeline" className="flex items-center gap-1 text-sm font-bold text-[#4b8174] hover:text-[#173f48]" data-testid="link-view-all-events">View timeline <ArrowUpRight className="h-4 w-4" /></Link></div><div className="space-y-3">{data.recentEvents.length ? data.recentEvents.map((event) => <EventRow key={event.id} event={event} profile={data.profiles.find((p) => p.id === event.profileId)} />) : <div className="rounded-2xl border border-dashed border-[#cbd6d0] p-8"><p className="font-serif text-lg">Your story starts here.</p><p className="mt-1 text-sm text-[#778683]">Add a visit, symptom, or note to make this space useful.</p></div>}</div></section><aside className="space-y-4"><div className="rounded-2xl bg-[#173f48] p-6 text-[#f8f6ec]"><div className="flex items-center justify-between"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#91b4aa]">Active profile</p><ShieldCheck className="h-5 w-5 text-[#efd47b]" /></div>{active ? <><div className="mt-5 flex items-center gap-3"><ProfileAvatar profile={active} size="md" /><div><h3 className="font-serif text-xl">{active.name}</h3><p className="text-xs text-[#a8c1b8]">{active.relationship} · {active.eventCount} memories</p></div></div><Link href={`/profiles/${active.id}`} className="mt-6 flex items-center justify-between border-t border-[#396a72] pt-4 text-sm font-bold text-[#efd47b]" data-testid={`link-active-profile-${active.id}`}>Open profile <ArrowUpRight className="h-4 w-4" /></Link></> : <p className="mt-4 text-sm text-[#a8c1b8]">Add your first family profile to begin.</p>}</div><div className="rounded-2xl border border-[#e4e5dc] bg-[#fffdf8] p-6"><p className="font-mono text-[10px] font-bold uppercase tracking-[.16em] text-[#66837d]">A quiet nudge</p><p className="mt-3 font-serif text-xl leading-snug text-[#173f48]">The details that feel small today become helpful later.</p><p className="mt-3 text-sm leading-6 text-[#788782]">You can keep your records light or detailed. There is no right way to remember.</p><Link href="/reminders" className="mt-5 inline-flex items-center gap-1 text-sm font-bold text-[#4b8174]" data-testid="link-nudge-reminders">Review reminders <ArrowUpRight className="h-4 w-4" /></Link></div></aside></div>
  </div>;
}