import { ArrowLeft, CheckCircle2, Clipboard, Clock3, FileText, Printer } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { getGetProfileSummaryQueryKey, useGetProfileSummary } from '@workspace/api-client-react';
import { Button, ErrorState, LoadingState, ProfileAvatar, formatDate } from '@/components/shared';

function SummaryBlock({ title, items, empty }: { title: string; items: string[]; empty: string }) {
  return <section className="border-t border-[#e2edf3] pt-6"><h2 className="text-xs font-bold uppercase tracking-[.1em] text-[#6c93aa]">{title}</h2>{items.length ? <ul className="mt-4 space-y-3">{items.map((item, index) => <li className="flex gap-3 text-[15px] leading-6 text-[#435f75]" key={`${item}-${index}`}><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#67a8cf]" />{item}</li>)}</ul> : <p className="mt-4 text-sm italic text-[#879dab]">{empty}</p>}</section>;
}

export default function SummaryPage() {
  const params = useParams<{ profileId: string }>();
  const id = Number(params.profileId);
  const summary = useGetProfileSummary(id, { query: { queryKey: getGetProfileSummaryQueryKey(id), enabled: !!id } });
  if (summary.isLoading) return <LoadingState lines={7} />;
  if (summary.isError || !summary.data) return <ErrorState onRetry={() => summary.refetch()} />;
  const data = summary.data;
  const print = () => window.print();
  const copy = async () => { await navigator.clipboard?.writeText(`${data.profile.name} — Health summary\n\n${data.overview}\n\nKey conditions:\n${data.keyConditions.join('\n')}\n\nCurrent medications:\n${data.currentMedications.join('\n')}`); };
  return <div className="animate-rise mx-auto max-w-[950px]" data-testid={`page-summary-${id}`}><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center print:hidden"><Link href={`/profiles/${id}`} className="inline-flex items-center gap-2 text-sm font-bold text-[#5c819a] hover:text-[#183b59]" data-testid="link-back-summary"><ArrowLeft className="h-4 w-4" />Back to {data.profile.name}</Link><div className="flex gap-2"><Button variant="outline" onClick={copy} data-testid="button-copy-summary"><Clipboard className="h-4 w-4" />Copy</Button><Button onClick={print} data-testid="button-print-summary"><Printer className="h-4 w-4" />Print / share</Button></div></div><article className="overflow-hidden rounded-[2rem] border border-[#d9edf8] bg-white shadow-[0_14px_40px_rgba(36,92,132,.07)] print:border-0 print:shadow-none"><div className="bg-[#eaf7ff] px-7 py-9 text-[#183b59] sm:px-12"><div className="flex items-start justify-between gap-5"><div><div className="flex items-center gap-2 text-[#3487b8]"><FileText className="h-5 w-5" /><span className="text-xs font-bold uppercase tracking-[.1em]">Health summary</span></div><h1 className="mt-7 font-serif text-4xl leading-tight sm:text-5xl">{data.profile.name}</h1><p className="mt-2 text-[#64839a]">{data.profile.relationship}{data.profile.dateOfBirth ? ` · Born ${formatDate(data.profile.dateOfBirth, 'long')}` : ''}{data.profile.bloodGroup ? ` · ${data.profile.bloodGroup}` : ''}</p></div><ProfileAvatar profile={data.profile} size="lg" /></div><div className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-2 border-t border-[#cce7f4] pt-5 text-xs text-[#66899f]"><span className="flex items-center gap-2"><Clock3 className="h-3.5 w-3.5" />Updated {formatDate(data.generatedAt, 'long')}</span><span>For conversation with a healthcare professional</span></div></div><div className="space-y-8 px-7 py-9 sm:px-12 sm:py-11"><section><h2 className="text-xs font-bold uppercase tracking-[.1em] text-[#6c93aa]">At a glance</h2><p className="mt-4 max-w-3xl font-serif text-2xl leading-[1.3] text-[#183b59]">{data.overview}</p></section><SummaryBlock title="Key conditions" items={data.keyConditions} empty="No conditions have been added to this summary." /><SummaryBlock title="Current medications" items={data.currentMedications} empty="No current medications have been added to this summary." /><div className="grid gap-8 sm:grid-cols-2"><SummaryBlock title="Recent tests" items={data.recentTests} empty="No recent tests recorded." /><SummaryBlock title="Recent visits" items={data.recentVisits} empty="No recent visits recorded." /></div><div className="flex gap-3 rounded-2xl bg-[#f0f9fe] p-4 text-sm leading-6 text-[#5e7d91]"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#4b98c4]" /><p>This summary is a clear starting point for a conversation. Bring the original details and your questions, too.</p></div></div></article></div>;
}